USE [inventario]
GO

/****** Object:  Table [SGBD].[SGBDTableColumn]    Script Date: 03/07/2021 20:24:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SGBD].[SGBDTableColumn](
	[idSGBDTableColumn] [int] IDENTITY(1,1) NOT NULL,
	[idSGBDTable] [int] NOT NULL,
	[colunn_name] [varchar](128) NULL,
	[ordenal_positon] [int] NULL,
	[data_type] [varchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[idSGBDTableColumn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SGBD].[SGBDTableColumn]  WITH CHECK ADD  CONSTRAINT [FK__SGBDTableColumn__idDat__32AB8735] FOREIGN KEY([idSGBDTable])
REFERENCES [SGBD].[SGBDTable] ([idSGBDTable])
GO

ALTER TABLE [SGBD].[SGBDTableColumn] CHECK CONSTRAINT [FK__SGBDTableColumn__idDat__32AB8735]
GO


